nav:
  - index.md
  - Frontend: frontend.md
  - ADX:
    - Overview: adx-database.md
    - Functions & Performance: adx-functions-performance.md
  - Power BI:
    - Overview: power-bi.md
    - Parameters & Reuse: power-bi-parameters.md
    - Embedding & Security: power-bi-embedding.md
