nav:
  - index.md
  - Git: git.md
  - Docker: docker.md
  - Babylon: babylon.md
  - kubectl: kubectl.md
  - Superset: superset.md
  - Azure CLI: az-cli.md
  - Terraform: terraform.md
  - Cosmo Tech SDK: cosmotech-sdk.md
